(deftheme hw
  "Created 2017-10-13.")

(custom-theme-set-variables
 'hw
 '(flycheck-color-mode-line-face-to-color (quote mode-line-buffer-id))
 '(ansi-color-names-vector ["#eaeaea" "#d54e53" "#b9ca4a" "#e7c547" "#7aa6da" "#c397d8" "#70c0b1" "#424242"])
 '(ansi-color-faces-vector [default bold shadow italic underline bold bold-italic bold]))

(custom-theme-set-faces
 'hw
 '(bold ((((class color) (min-colors 89)) (:weight bold))))
 '(bold-italic ((((class color) (min-colors 89)) (:slant italic :weight bold))))
 '(underline ((((class color) (min-colors 89)) (:underline t))))
 '(italic ((((class color) (min-colors 89)) (:slant italic))))
 '(font-lock-builtin-face ((t (:foreground "#ffff00"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#969696" :slant italic))))
 '(font-lock-comment-face ((t (:foreground "#969696" :slant italic))))
 '(font-lock-constant-face ((t (:foreground "#ff00ff"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(font-lock-doc-string-face ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(font-lock-function-name-face ((t (:foreground "#00ffff"))))
 '(font-lock-keyword-face ((t (:foreground "#ffff00"))))
 '(font-lock-negation-char-face ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(font-lock-preprocessor-face ((t (:foreground "#0000ff"))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(font-lock-string-face ((t (:foreground "#ff00ff"))))
 '(font-lock-type-face ((t (:foreground "#00ff00"))))
 '(font-lock-variable-name-face ((t (:foreground "#ffffff"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:weight bold :foreground "#d54e53"))))
 '(shadow ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(success ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(error ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(tooltip ((((class color) (min-colors 89)) (:foreground "#e7c547" :background "#000000" :inverse-video t))))
 '(window-divider ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(window-divider-first-pixel ((((class color) (min-colors 89)) (:foreground "#424242"))))
 '(window-divider-last-pixel ((((class color) (min-colors 89)) (:foreground "#424242"))))
 '(aw-background-face ((((class color) (min-colors 89)) (:foreground "#424242"))))
 '(aw-leading-char-face ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(avy-background-face ((((class color) (min-colors 89)) (:foreground "#424242"))))
 '(avy-lead-face ((((class color) (min-colors 89)) (:foreground "#000000" :background "#e7c547"))))
 '(avy-lead-face-0 ((((class color) (min-colors 89)) (:foreground "#000000" :background "#7aa6da"))))
 '(avy-lead-face-1 ((((class color) (min-colors 89)) (:foreground "#000000" :background "#70c0b1"))))
 '(avy-lead-face-2 ((((class color) (min-colors 89)) (:foreground "#000000" :background "#e78c45"))))
 '(bmkp-*-mark ((((class color) (min-colors 89)) (:foreground "#000000" :background "#e7c547"))))
 '(bmkp->-mark ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(bmkp-D-mark ((((class color) (min-colors 89)) (:foreground "#000000" :background "#d54e53"))))
 '(bmkp-X-mark ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(bmkp-a-mark ((((class color) (min-colors 89)) (:background "#d54e53"))))
 '(bmkp-bad-bookmark ((((class color) (min-colors 89)) (:foreground "#000000" :background "#e7c547"))))
 '(bmkp-bookmark-file ((((class color) (min-colors 89)) (:foreground "#c397d8" :background "#424242"))))
 '(bmkp-bookmark-list ((((class color) (min-colors 89)) (:background "#424242"))))
 '(bmkp-buffer ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(bmkp-desktop ((((class color) (min-colors 89)) (:foreground "#000000" :background "#c397d8"))))
 '(bmkp-file-handler ((((class color) (min-colors 89)) (:background "#d54e53"))))
 '(bmkp-function ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(bmkp-gnus ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(bmkp-heading ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(bmkp-info ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(bmkp-light-autonamed ((((class color) (min-colors 89)) (:foreground "#70c0b1" :background "#2a2a2a"))))
 '(bmkp-light-autonamed-region ((((class color) (min-colors 89)) (:foreground "#d54e53" :background "#2a2a2a"))))
 '(bmkp-light-fringe-autonamed ((((class color) (min-colors 89)) (:foreground "#424242" :background "#c397d8"))))
 '(bmkp-light-fringe-non-autonamed ((((class color) (min-colors 89)) (:foreground "#424242" :background "#b9ca4a"))))
 '(bmkp-light-mark ((((class color) (min-colors 89)) (:foreground "#000000" :background "#70c0b1"))))
 '(bmkp-light-non-autonamed ((((class color) (min-colors 89)) (:foreground "#c397d8" :background "#2a2a2a"))))
 '(bmkp-light-non-autonamed-region ((((class color) (min-colors 89)) (:foreground "#e78c45" :background "#2a2a2a"))))
 '(bmkp-local-directory ((((class color) (min-colors 89)) (:foreground "#000000" :background "#c397d8"))))
 '(bmkp-local-file-with-region ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(bmkp-local-file-without-region ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(bmkp-man ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(bmkp-no-jump ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(bmkp-no-local ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(bmkp-non-file ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(bmkp-remote-file ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(bmkp-sequence ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(bmkp-su-or-sudo ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(bmkp-t-mark ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(bmkp-url ((((class color) (min-colors 89)) (:foreground "#7aa6da" :underline t))))
 '(bmkp-variable-list ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(flycheck-error ((((class color) (min-colors 89)) (:underline (:style wave :color "#d54e53")))))
 '(flycheck-info ((((class color) (min-colors 89)) (:underline (:style wave :color "#70c0b1")))))
 '(flycheck-warning ((((class color) (min-colors 89)) (:underline (:style wave :color "#e78c45")))))
 '(flycheck-fringe-error ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(flycheck-fringe-info ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(flycheck-fringe-warning ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(flycheck-color-mode-line-error-face ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(flycheck-color-mode-line-warning-face ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(flycheck-color-mode-line-info-face ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(flycheck-color-mode-line-running-face ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(flycheck-color-mode-line-success-face ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(flymake-warnline ((((class color) (min-colors 89)) (:underline (:style wave :color "#e78c45") :background "#000000"))))
 '(flymake-errline ((((class color) (min-colors 89)) (:underline (:style wave :color "#d54e53") :background "#000000"))))
 '(flyspell-incorrect ((((class color) (min-colors 89)) (:underline (:style wave :color "#d54e53")))))
 '(lispy-command-name-face ((((class color) (min-colors 89)) (:inherit font-lock-function-name-face :background "#2a2a2a"))))
 '(lispy-cursor-face ((((class color) (min-colors 89)) (:foreground "#000000" :background "#eaeaea"))))
 '(lispy-face-hint ((((class color) (min-colors 89)) (:foreground "#b9ca4a" :background "#424242"))))
 '(clojure-test-failure-face ((((class color) (min-colors 89)) (:background nil :inherit flymake-warnline))))
 '(clojure-test-error-face ((((class color) (min-colors 89)) (:background nil :inherit flymake-errline))))
 '(clojure-test-success-face ((((class color) (min-colors 89)) (:background nil :foreground nil :underline "#b9ca4a"))))
 '(edts-face-warning-line ((((class color) (min-colors 89)) (:background nil :inherit flymake-warnline))))
 '(edts-face-warning-mode-line ((((class color) (min-colors 89)) (:background nil :foreground "#e78c45" :weight bold))))
 '(edts-face-error-line ((((class color) (min-colors 89)) (:background nil :inherit flymake-errline))))
 '(edts-face-error-mode-line ((((class color) (min-colors 89)) (:background nil :foreground "#d54e53" :weight bold))))
 '(clojure-keyword ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(clojure-parens ((((class color) (min-colors 89)) (:foreground "#eaeaea"))))
 '(clojure-braces ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(clojure-brackets ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(clojure-double-quote ((((class color) (min-colors 89)) (:foreground "#70c0b1" :background nil))))
 '(clojure-special ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(clojure-java-call ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(rainbow-delimiters-depth-1-face ((((class color) (min-colors 89)) (:foreground "#eaeaea"))))
 '(rainbow-delimiters-depth-2-face ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(rainbow-delimiters-depth-3-face ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(rainbow-delimiters-depth-4-face ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(rainbow-delimiters-depth-5-face ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(rainbow-delimiters-depth-6-face ((((class color) (min-colors 89)) (:foreground "#eaeaea"))))
 '(rainbow-delimiters-depth-7-face ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(rainbow-delimiters-depth-8-face ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(rainbow-delimiters-depth-9-face ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(rainbow-delimiters-unmatched-face ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(mmm-code-submode-face ((((class color) (min-colors 89)) (:background "#424242"))))
 '(mmm-comment-submode-face ((((class color) (min-colors 89)) (:inherit font-lock-comment-face))))
 '(mmm-output-submode-face ((((class color) (min-colors 89)) (:background "#424242"))))
 '(match ((((class color) (min-colors 89)) (:foreground "#7aa6da" :background "#000000" :inverse-video t))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "#e7c547" :background "#000000" :inverse-video t))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:foreground "#70c0b1" :background "#000000" :inverse-video t))))
 '(isearch-fail ((((class color) (min-colors 89)) (:background "#000000" :inherit font-lock-warning-face :inverse-video t))))
 '(anzu-mode-line ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(anzu-mode-line-no-match ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(anzu-replace-highlight ((((class color) (min-colors 89)) (:inherit isearch-lazy-highlight-face))))
 '(anzu-replace-to ((((class color) (min-colors 89)) (:inherit isearch))))
 '(anzu-match-1 ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(anzu-match-2 ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(anzu-match-3 ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(ido-subdir ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(ido-first-match ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(ido-only-match ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(ido-indicator ((((class color) (min-colors 89)) (:foreground "#d54e53" :background "#000000"))))
 '(ido-virtual ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(flx-highlight-face ((((class color) (min-colors 89)) (:inherit nil :foreground "#e7c547" :weight bold :underline nil))))
 '(ivy-action ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(ivy-confirm-face ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(ivy-current-match ((((class color) (min-colors 89)) (:foreground "#b9ca4a" :inherit highlight :underline t))))
 '(ivy-cursor ((((class color) (min-colors 89)) (:background "#424242"))))
 '(ivy-match-required-face ((((class color) (min-colors 89)) (:inherit ido-indicator))))
 '(ivy-remote ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(ivy-subdir ((((class color) (min-colors 89)) (:inherit ido-subdir))))
 '(ivy-virtual ((((class color) (min-colors 89)) (:inherit ido-virtual))))
 '(ivy-minibuffer-match-face-1 ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(ivy-minibuffer-match-face-2 ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(ivy-minibuffer-match-face-3 ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(ivy-minibuffer-match-face-4 ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(which-func ((((class color) (min-colors 89)) (:foreground "#7aa6da" :background nil :weight bold))))
 '(cursor ((t (:background "#ee82ee"))))
 '(fringe ((((class color) (min-colors 89)) (:background "#151515" :foreground "#969896"))))
 '(linum ((((class color) (min-colors 89)) (:background "#151515" :foreground "#969896" :italic nil :underline nil))))
 '(line-number ((((class color) (min-colors 89)) (:background "#151515" :foreground "#969896"))))
 '(line-number-current-line ((((class color) (min-colors 89)) (:inherit line-number :foreground "#eaeaea"))))
 '(vertical-border ((((class color) (min-colors 89)) (:foreground "#424242"))))
 '(border ((((class color) (min-colors 89)) (:background "#424242" :foreground "#2a2a2a"))))
 '(border-glyph ((((class color) (min-colors 89)) (nil))))
 '(highlight ((((class color) (min-colors 89)) (:inverse-video nil :background "#2a2a2a"))))
 '(gui-element ((((class color) (min-colors 89)) (:background "#424242" :foreground "#eaeaea"))))
 '(mode-line ((((class color) (min-colors 89)) (:foreground "#eaeaea" :background "#424242" :weight normal :box (:line-width 1 :color "#424242")))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:foreground "#c397d8" :background nil))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:inherit mode-line :foreground "#969896" :background "#2a2a2a" :weight normal))))
 '(mode-line-emphasis ((((class color) (min-colors 89)) (:foreground "#eaeaea" :slant italic))))
 '(mode-line-highlight ((((class color) (min-colors 89)) (:foreground "#c397d8" :box nil :weight bold))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(region ((((class color) (min-colors 89)) (:background "#424242" :inverse-video nil))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "#2a2a2a"))))
 '(header-line ((((class color) (min-colors 89)) (:inherit mode-line-inactive :foreground "#70c0b1" :background nil))))
 '(whitespace-big-indent ((((class color) (min-colors 89)) (:background "#d54e53" :foreground "#424242"))))
 '(whitespace-empty ((((class color) (min-colors 89)) (:background "#e7c547" :foreground "#e78c45"))))
 '(whitespace-hspace ((((class color) (min-colors 89)) (:background "#424242" :foreground "#969896"))))
 '(whitespace-indentation ((((class color) (min-colors 89)) (:background "#424242" :foreground "#969896"))))
 '(whitespace-line ((((class color) (min-colors 89)) (:background "#424242" :foreground "#e78c45"))))
 '(whitespace-newline ((((class color) (min-colors 89)) (:background "#424242" :foreground "#969896"))))
 '(whitespace-space ((((class color) (min-colors 89)) (:background "#424242" :foreground "#969896"))))
 '(whitespace-space-after-tab ((((class color) (min-colors 89)) (:background "#424242" :foreground "#e7c547"))))
 '(whitespace-space-before-tab ((((class color) (min-colors 89)) (:background "#424242" :foreground "#e78c45"))))
 '(whitespace-tab ((((class color) (min-colors 89)) (:background "#424242" :foreground "#969896"))))
 '(whitespace-trailing ((((class color) (min-colors 89)) (:background "#e78c45" :foreground "#424242"))))
 '(trailing-whitespace ((((class color) (min-colors 89)) (:inherit whitespace-trailing))))
 '(show-paren-match ((((class color) (min-colors 89)) (:background "#c397d8" :foreground "#000000"))))
 '(show-paren-mismatch ((((class color) (min-colors 89)) (:background "#d54e53" :foreground "#000000"))))
 '(sp-show-pair-match-face ((((class color) (min-colors 89)) (:foreground nil :background nil :inherit show-paren-match))))
 '(sp-show-pair-mismatch-face ((((class color) (min-colors 89)) (:foreground nil :background nil :inherit show-paren-mismatch))))
 '(paren-face-match ((((class color) (min-colors 89)) (:foreground nil :background nil :inherit show-paren-match))))
 '(paren-face-mismatch ((((class color) (min-colors 89)) (:foreground nil :background nil :inherit show-paren-mismatch))))
 '(paren-face-no-match ((((class color) (min-colors 89)) (:foreground nil :background nil :inherit show-paren-mismatch))))
 '(paren-face ((((class color) (min-colors 89)) (:foreground "#969896" :background nil))))
 '(sh-heredoc ((((class color) (min-colors 89)) (:foreground nil :inherit font-lock-string-face :weight normal))))
 '(sh-quoted-exec ((((class color) (min-colors 89)) (:foreground nil :inherit font-lock-preprocessor-face))))
 '(slime-highlight-edits-face ((((class color) (min-colors 89)) (:weight bold))))
 '(slime-repl-input-face ((((class color) (min-colors 89)) (:weight normal :underline nil))))
 '(slime-repl-prompt-face ((((class color) (min-colors 89)) (:underline nil :weight bold :foreground "#c397d8"))))
 '(slime-repl-result-face ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(slime-repl-output-face ((((class color) (min-colors 89)) (:foreground "#7aa6da" :background "#000000"))))
 '(slime-repl-inputed-output-face ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(csv-separator-face ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(diff-added ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(diff-changed ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(diff-removed ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(diff-header ((((class color) (min-colors 89)) (:foreground "#70c0b1" :background nil))))
 '(diff-file-header ((((class color) (min-colors 89)) (:foreground "#7aa6da" :background nil))))
 '(diff-hunk-header ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(diff-refine-added ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(diff-refine-removed ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(diff-hl-insert ((((class color) (min-colors 89)) (:background "#b9ca4a"))))
 '(diff-hl-change ((((class color) (min-colors 89)) (:background "#7aa6da"))))
 '(diff-hl-delete ((((class color) (min-colors 89)) (:background "#e78c45"))))
 '(diff-hl-unknown ((((class color) (min-colors 89)) (:background "#c397d8"))))
 '(ediff-current-diff-A ((((class color) (min-colors 89)) (:foreground "#969896" :background "#2a2a2a"))))
 '(ediff-current-diff-Ancestor ((((class color) (min-colors 89)) (:foreground "#70c0b1" :background "#2a2a2a"))))
 '(ediff-current-diff-B ((((class color) (min-colors 89)) (:foreground "#969896" :background "#2a2a2a"))))
 '(ediff-current-diff-C ((((class color) (min-colors 89)) (:foreground "#969896" :background "#2a2a2a"))))
 '(ediff-even-diff-A ((((class color) (min-colors 89)) (:foreground "#7aa6da" :background "#424242"))))
 '(ediff-even-diff-Ancestor ((((class color) (min-colors 89)) (:foreground "#c397d8" :background "#2a2a2a"))))
 '(ediff-even-diff-B ((((class color) (min-colors 89)) (:foreground "#7aa6da" :background "#424242"))))
 '(ediff-even-diff-C ((((class color) (min-colors 89)) (:foreground "#7aa6da" :background "#424242"))))
 '(ediff-fine-diff-A ((((class color) (min-colors 89)) (:foreground "#b9ca4a" :background "#424242"))))
 '(ediff-fine-diff-Ancestor ((((class color) (min-colors 89)) (:foreground "#e7c547" :background "#2a2a2a"))))
 '(ediff-fine-diff-B ((((class color) (min-colors 89)) (:foreground "#b9ca4a" :background "#424242"))))
 '(ediff-fine-diff-C ((((class color) (min-colors 89)) (:foreground "#b9ca4a" :background "#424242"))))
 '(ediff-odd-diff-A ((((class color) (min-colors 89)) (:foreground "#e78c45" :background "#424242"))))
 '(ediff-odd-diff-Ancestor ((((class color) (min-colors 89)) (:foreground "#d54e53" :background "#2a2a2a"))))
 '(ediff-odd-diff-B ((((class color) (min-colors 89)) (:foreground "#e78c45" :background "#424242"))))
 '(ediff-odd-diff-C ((((class color) (min-colors 89)) (:foreground "#e78c45" :background "#424242"))))
 '(eldoc-highlight-function-argument ((((class color) (min-colors 89)) (:foreground "#b9ca4a" :weight bold))))
 '(macrostep-expansion-highlight-face ((((class color) (min-colors 89)) (:inherit highlight :foreground nil))))
 '(ert-test-result-unexpected ((((class color) (min-colors 89)) (:inherit error))))
 '(ert-test-result-expected ((((class color) (min-colors 89)) (:inherit success))))
 '(undo-tree-visualizer-default-face ((((class color) (min-colors 89)) (:foreground "#eaeaea"))))
 '(undo-tree-visualizer-current-face ((((class color) (min-colors 89)) (:foreground "#b9ca4a" :weight bold))))
 '(undo-tree-visualizer-active-branch-face ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(undo-tree-visualizer-register-face ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(diredfl-compressed-file-suffix ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(diredfl-compressed-file-name ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(diredfl-deletion ((((class color) (min-colors 89)) (:inherit error :inverse-video t))))
 '(diredfl-deletion-file-name ((((class color) (min-colors 89)) (:inherit error))))
 '(diredfl-date-time ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(diredfl-dir-heading ((((class color) (min-colors 89)) (:foreground "#b9ca4a" :weight bold))))
 '(diredfl-dir-name ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(diredfl-dir-priv ((((class color) (min-colors 89)) (:foreground "#70c0b1" :background nil))))
 '(diredfl-exec-priv ((((class color) (min-colors 89)) (:foreground "#e78c45" :background nil))))
 '(diredfl-executable-tag ((((class color) (min-colors 89)) (:foreground "#d54e53" :background nil))))
 '(diredfl-file-name ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(diredfl-file-suffix ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(diredfl-flag-mark ((((class color) (min-colors 89)) (:foreground "#b9ca4a" :inverse-video t))))
 '(diredfl-flag-mark-line ((((class color) (min-colors 89)) (:background nil :inherit highlight))))
 '(diredfl-ignored-file-name ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(diredfl-link-priv ((((class color) (min-colors 89)) (:background nil :foreground "#c397d8"))))
 '(diredfl-mode-line-flagged ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(diredfl-mode-line-marked ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(diredfl-no-priv ((((class color) (min-colors 89)) (:background nil))))
 '(diredfl-number ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(diredfl-other-priv ((((class color) (min-colors 89)) (:background nil :foreground "#c397d8"))))
 '(diredfl-rare-priv ((((class color) (min-colors 89)) (:foreground "#d54e53" :background nil))))
 '(diredfl-read-priv ((((class color) (min-colors 89)) (:foreground "#b9ca4a" :background nil))))
 '(diredfl-symlink ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(diredfl-write-priv ((((class color) (min-colors 89)) (:foreground "#e7c547" :background nil))))
 '(diredp-compressed-file-suffix ((((class color) (min-colors 89)) (:inherit diredfl-compressed-file-suffix))))
 '(diredp-compressed-file-name ((((class color) (min-colors 89)) (:inherit diredfl-compressed-file-name))))
 '(diredp-deletion ((((class color) (min-colors 89)) (:inherit diredfl-deletion))))
 '(diredp-deletion-file-name ((((class color) (min-colors 89)) (:inherit diredfl-deletion-file-name))))
 '(diredp-date-time ((((class color) (min-colors 89)) (:inherit diredfl-date-time))))
 '(diredp-dir-heading ((((class color) (min-colors 89)) (:inherit diredfl-dir-heading))))
 '(diredp-dir-name ((((class color) (min-colors 89)) (:inherit diredfl-dir-name))))
 '(diredp-dir-priv ((((class color) (min-colors 89)) (:inherit diredfl-dir-priv))))
 '(diredp-exec-priv ((((class color) (min-colors 89)) (:inherit diredfl-exec-priv))))
 '(diredp-executable-tag ((((class color) (min-colors 89)) (:inherit diredfl-executable-tag))))
 '(diredp-file-name ((((class color) (min-colors 89)) (:inherit diredfl-file-name))))
 '(diredp-file-suffix ((((class color) (min-colors 89)) (:inherit diredfl-file-suffix))))
 '(diredp-flag-mark ((((class color) (min-colors 89)) (:inherit diredfl-flag-mark))))
 '(diredp-flag-mark-line ((((class color) (min-colors 89)) (:inherit diredfl-flag-mark-line))))
 '(diredp-ignored-file-name ((((class color) (min-colors 89)) (:inherit diredfl-ignored-file-name))))
 '(diredp-link-priv ((((class color) (min-colors 89)) (:inherit diredfl-link-priv))))
 '(diredp-mode-line-flagged ((((class color) (min-colors 89)) (:inherit diredfl-mode-line-flagged))))
 '(diredp-mode-line-marked ((((class color) (min-colors 89)) (:inherit diredfl-mode-line-marked))))
 '(diredp-no-priv ((((class color) (min-colors 89)) (:inherit diredfl-no-priv))))
 '(diredp-number ((((class color) (min-colors 89)) (:inherit diredfl-number))))
 '(diredp-other-priv ((((class color) (min-colors 89)) (:inherit diredfl-other-priv))))
 '(diredp-rare-priv ((((class color) (min-colors 89)) (:inherit diredfl-rare-priv))))
 '(diredp-read-priv ((((class color) (min-colors 89)) (:inherit diredfl-read-priv))))
 '(diredp-symlink ((((class color) (min-colors 89)) (:inherit diredfl-symlink))))
 '(diredp-write-priv ((((class color) (min-colors 89)) (:inherit diredfl-write-priv))))
 '(dired-async-failures ((((class color) (min-colors 89)) (:inherit error))))
 '(dired-async-message ((((class color) (min-colors 89)) (:inherit success))))
 '(dired-async-mode-message ((((class color) (min-colors 89)) (:inherit warning))))
 '(neo-banner-face ((((class color) (min-colors 89)) (:foreground "#7aa6da" :weight bold))))
 '(neo-button-face ((((class color) (min-colors 89)) (:underline t))))
 '(neo-dir-link-face ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(neo-expand-btn-face ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(neo-file-link-face ((((class color) (min-colors 89)) (:foreground "#eaeaea"))))
 '(neo-header-face ((((class color) (min-colors 89)) (:foreground "#eaeaea" :background "#2a2a2a"))))
 '(neo-root-dir-face ((((class color) (min-colors 89)) (:foreground "#7aa6da" :weight bold))))
 '(neo-vc-added-face ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(neo-vc-conflict-face ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(neo-vc-default-face ((((class color) (min-colors 89)) (:foreground "#eaeaea"))))
 '(neo-vc-edited-face ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(neo-vc-ignored-face ((((class color) (min-colors 89)) (:foreground "#424242"))))
 '(neo-vc-missing-face ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(neo-vc-needs-merge-face ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(neo-vc-unlocked-changes-face ((((class color) (min-colors 89)) (:foreground "#7aa6da" :slant italic))))
 '(neo-vc-user-face ((((class color) (min-colors 89)) (:foreground "#d54e53" :slant italic))))
 '(speedbar-button-face ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(speedbar-directory-face ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(speedbar-file-face ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(speedbar-highlight-face ((((class color) (min-colors 89)) (:inherit highlight))))
 '(speedbar-selected-face ((((class color) (min-colors 89)) (:foreground "#d54e53" :underline t))))
 '(speedbar-separator-face ((((class color) (min-colors 89)) (:foreground "#000000" :background "#7aa6da" :overline "#000000"))))
 '(speedbar-tag-face ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(vhdl-speedbar-architecture-face ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(vhdl-speedbar-architecture-selected-face ((((class color) (min-colors 89)) (:foreground "#7aa6da" :underline t))))
 '(vhdl-speedbar-configuration-face ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(vhdl-speedbar-configuration-selected-face ((((class color) (min-colors 89)) (:foreground "#b9ca4a" :underline t))))
 '(vhdl-speedbar-entity-face ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(vhdl-speedbar-entity-selected-face ((((class color) (min-colors 89)) (:foreground "#e78c45" :underline t))))
 '(vhdl-speedbar-instantiation-face ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(vhdl-speedbar-instantiation-selected-face ((((class color) (min-colors 89)) (:foreground "#e7c547" :underline t))))
 '(vhdl-speedbar-library-face ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(vhdl-speedbar-package-face ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(vhdl-speedbar-package-selected-face ((((class color) (min-colors 89)) (:foreground "#70c0b1" :underline t))))
 '(vhdl-speedbar-subprogram-face ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(magit-bisect-bad ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(magit-bisect-good ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(magit-bisect-skip ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(magit-blame-date ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(magit-blame-heading ((((class color) (min-colors 89)) (:foreground "#e78c45" :background "#2a2a2a"))))
 '(magit-branch-current ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(magit-branch-local ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(magit-branch-remote ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(magit-cherry-equivalent ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(magit-cherry-unmatched ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(magit-diff-added ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(magit-diff-added-highlight ((((class color) (min-colors 89)) (:foreground "#b9ca4a" :background "#2a2a2a"))))
 '(magit-diff-base ((((class color) (min-colors 89)) (:foreground "#000000" :background "#e78c45"))))
 '(magit-diff-base-highlight ((((class color) (min-colors 89)) (:foreground "#e78c45" :background "#2a2a2a"))))
 '(magit-diff-context ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(magit-diff-context-highlight ((((class color) (min-colors 89)) (:foreground "#969896" :background "#2a2a2a"))))
 '(magit-diff-file-heading ((((class color) (min-colors 89)) (:foreground "#eaeaea"))))
 '(magit-diff-file-heading-highlight ((((class color) (min-colors 89)) (:background "#424242" :weight bold))))
 '(magit-diff-file-heading-selection ((((class color) (min-colors 89)) (:foreground "#e78c45" :background "#2a2a2a"))))
 '(magit-diff-hunk-heading ((((class color) (min-colors 89)) (:foreground "#eaeaea" :background "#424242"))))
 '(magit-diff-hunk-heading-highlight ((((class color) (min-colors 89)) (:background "#424242"))))
 '(magit-diff-lines-heading ((((class color) (min-colors 89)) (:foreground "#e7c547" :background "#d54e53"))))
 '(magit-diff-removed ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(magit-diff-removed-highlight ((((class color) (min-colors 89)) (:foreground "#e78c45" :background "#2a2a2a"))))
 '(magit-diffstat-added ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(magit-diffstat-removed ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(magit-dimmed ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(magit-hash ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(magit-header-line ((((class color) (min-colors 89)) (:inherit nil :weight bold))))
 '(magit-log-author ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(magit-log-date ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(magit-log-graph ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(magit-process-ng ((((class color) (min-colors 89)) (:inherit error))))
 '(magit-process-ok ((((class color) (min-colors 89)) (:inherit success))))
 '(magit-reflog-amend ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(magit-reflog-checkout ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(magit-reflog-cherry-pick ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(magit-reflog-commit ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(magit-reflog-merge ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(magit-reflog-other ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(magit-reflog-rebase ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(magit-reflog-remote ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(magit-reflog-reset ((((class color) (min-colors 89)) (:inherit error))))
 '(magit-refname ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(magit-section-heading ((((class color) (min-colors 89)) (:foreground "#e7c547" :weight bold))))
 '(magit-section-heading-selection ((((class color) (min-colors 89)) (:foreground "#e78c45" :weight bold))))
 '(magit-section-highlight ((((class color) (min-colors 89)) (:background "#2a2a2a" :weight bold))))
 '(magit-sequence-drop ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(magit-sequence-head ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(magit-sequence-part ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(magit-sequence-stop ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(magit-signature-bad ((((class color) (min-colors 89)) (:inherit error))))
 '(magit-signature-error ((((class color) (min-colors 89)) (:inherit error))))
 '(magit-signature-expired ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(magit-signature-good ((((class color) (min-colors 89)) (:inherit success))))
 '(magit-signature-revoked ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(magit-signature-untrusted ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(magit-tag ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(git-gutter:modified ((((class color) (min-colors 89)) (:foreground "#c397d8" :weight bold))))
 '(git-gutter:added ((((class color) (min-colors 89)) (:foreground "#b9ca4a" :weight bold))))
 '(git-gutter:deleted ((((class color) (min-colors 89)) (:foreground "#d54e53" :weight bold))))
 '(git-gutter:unchanged ((((class color) (min-colors 89)) (:background "#e7c547"))))
 '(git-gutter-fr:modified ((((class color) (min-colors 89)) (:foreground "#c397d8" :weight bold))))
 '(git-gutter-fr:added ((((class color) (min-colors 89)) (:foreground "#b9ca4a" :weight bold))))
 '(git-gutter-fr:deleted ((((class color) (min-colors 89)) (:foreground "#d54e53" :weight bold))))
 '(guide-key/prefix-command-face ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(guide-key/highlight-command-face ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(guide-key/key-face ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(link ((((class color) (min-colors 89)) (:foreground nil :underline t))))
 '(widget-button ((((class color) (min-colors 89)) (:underline t))))
 '(widget-field ((((class color) (min-colors 89)) (:background "#424242" :box (:line-width 1 :color "#eaeaea")))))
 '(compilation-column-number ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(compilation-line-number ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(compilation-message-face ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(compilation-mode-line-exit ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(compilation-mode-line-fail ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(compilation-mode-line-run ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(grep-context-face ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(grep-error-face ((((class color) (min-colors 89)) (:foreground "#d54e53" :weight bold :underline t))))
 '(grep-hit-face ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(grep-match-face ((((class color) (min-colors 89)) (:foreground nil :background nil :inherit match))))
 '(wgrep-delete-face ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(wgrep-done-face ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(wgrep-face ((((class color) (min-colors 89)) (:foreground "#b9ca4a" :background "#424242"))))
 '(wgrep-file-face ((((class color) (min-colors 89)) (:foreground "#969896" :background "#424242"))))
 '(wgrep-reject-face ((((class color) (min-colors 89)) (:foreground "#e78c45" :weight bold))))
 '(regex-tool-matched-face ((((class color) (min-colors 89)) (:foreground nil :background nil :inherit match))))
 '(reb-match-0 ((((class color) (min-colors 89)) (:foreground "#000000" :background "#70c0b1"))))
 '(reb-match-1 ((((class color) (min-colors 89)) (:foreground "#000000" :background "#e7c547"))))
 '(reb-match-2 ((((class color) (min-colors 89)) (:foreground "#000000" :background "#e78c45"))))
 '(reb-match-3 ((((class color) (min-colors 89)) (:foreground "#000000" :background "#7aa6da"))))
 '(mm/master-face ((((class color) (min-colors 89)) (:inherit region :foreground nil :background nil))))
 '(mm/mirror-face ((((class color) (min-colors 89)) (:inherit region :foreground nil :background nil))))
 '(helm-buffer-saved-out ((((class color) (min-colors 89)) (:inherit warning))))
 '(helm-buffer-size ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(helm-buffer-not-saved ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(helm-buffer-process ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(helm-buffer-directory ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(helm-ff-dotted-directory ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(helm-ff-dotted-symlink-directory ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(helm-ff-directory ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(helm-candidate-number ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(helm-match ((((class color) (min-colors 89)) (:inherit match))))
 '(helm-selection ((((class color) (min-colors 89)) (:inherit highlight))))
 '(helm-separator ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(helm-source-header ((((class color) (min-colors 89)) (:weight bold :foreground "#e78c45" :height 1.44))))
 '(company-preview ((((class color) (min-colors 89)) (:foreground "#969896" :background "#424242"))))
 '(company-preview-common ((((class color) (min-colors 89)) (:inherit company-preview :foreground "#d54e53"))))
 '(company-preview-search ((((class color) (min-colors 89)) (:inherit company-preview :foreground "#7aa6da"))))
 '(company-tooltip ((((class color) (min-colors 89)) (:background "#424242"))))
 '(company-tooltip-selection ((((class color) (min-colors 89)) (:foreground "#969896" :inverse-video t))))
 '(company-tooltip-common ((((class color) (min-colors 89)) (:inherit company-tooltip :foreground "#d54e53"))))
 '(company-tooltip-common-selection ((((class color) (min-colors 89)) (:inherit company-tooltip-selection :foreground "#d54e53"))))
 '(company-tooltip-search ((((class color) (min-colors 89)) (:inherit company-tooltip :foreground "#7aa6da"))))
 '(company-tooltip-annotation ((((class color) (min-colors 89)) (:inherit company-tooltip :foreground "#b9ca4a"))))
 '(company-tooltip-annotation-selection ((((class color) (min-colors 89)) (:inherit company-tooltip-selection :foreground "#b9ca4a"))))
 '(company-scrollbar-bg ((((class color) (min-colors 89)) (:inherit (quote company-tooltip) :background "#2a2a2a"))))
 '(company-scrollbar-fg ((((class color) (min-colors 89)) (:background "#424242"))))
 '(company-echo-common ((((class color) (min-colors 89)) (:inherit company-echo :foreground "#d54e53"))))
 '(diary ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(holiday ((((class color) (min-colors 89)) (:foreground "#000000" :background "#e78c45"))))
 '(org-agenda-structure ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(org-agenda-current-time ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(org-agenda-date ((((class color) (min-colors 89)) (:foreground "#7aa6da" :underline nil))))
 '(org-agenda-done ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(org-agenda-dimmed-todo-face ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(org-block ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(org-code ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(org-column ((((class color) (min-colors 89)) (:background "#424242"))))
 '(org-column-title ((((class color) (min-colors 89)) (:inherit org-column :weight bold :underline t))))
 '(org-date ((((class color) (min-colors 89)) (:foreground "#7aa6da" :underline t))))
 '(org-document-info ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(org-document-info-keyword ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(org-document-title ((((class color) (min-colors 89)) (:weight bold :foreground "#e78c45" :height 1.44))))
 '(org-done ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(org-ellipsis ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(org-footnote ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(org-formula ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(org-hide ((((class color) (min-colors 89)) (:foreground "#000000" :background "#000000"))))
 '(org-link ((((class color) (min-colors 89)) (:foreground "#7aa6da" :underline t))))
 '(org-scheduled ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(org-scheduled-previously ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(org-scheduled-today ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(org-special-keyword ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(org-table ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(org-time-grid ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(org-todo ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(org-upcoming-deadline ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(org-warning ((((class color) (min-colors 89)) (:weight bold :foreground "#d54e53"))))
 '(markdown-url-face ((((class color) (min-colors 89)) (:inherit link))))
 '(markdown-link-face ((((class color) (min-colors 89)) (:foreground "#7aa6da" :underline t))))
 '(markdown-code-face ((((class color) (min-colors 89)) (:inherit fixed-pitch :background "#000000" :foreground "#c397d8"))))
 '(markdown-inline-code-face ((((class color) (min-colors 89)) (:inherit markdown-code-face))))
 '(Info-quoted ((((class color) (min-colors 89)) (:inherit font-lock-constant-face))))
 '(info-index-match ((((class color) (min-colors 89)) (:inherit isearch))))
 '(info-menu-header ((((class color) (min-colors 89)) (:foreground "#b9ca4a" :weight bold :height 1.4))))
 '(info-menu-star ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(info-node ((((class color) (min-colors 89)) (:foreground "#b9ca4a" :weight bold :slant italic))))
 '(info-title-1 ((((class color) (min-colors 89)) (:weight bold :height 1.6))))
 '(info-title-2 ((((class color) (min-colors 89)) (:weight bold :height 1.4))))
 '(info-title-3 ((((class color) (min-colors 89)) (:weight bold :height 1.2))))
 '(info-title-4 ((((class color) (min-colors 89)) (:weight bold))))
 '(info-xref-visited ((((class color) (min-colors 89)) (:foreground "#969896" :underline t))))
 '(info-command-ref-item ((((class color) (min-colors 89)) (:foreground "#b9ca4a" :background "#2a2a2a"))))
 '(info-constant-ref-item ((((class color) (min-colors 89)) (:foreground "#c397d8" :background "#2a2a2a"))))
 '(info-double-quoted-name ((((class color) (min-colors 89)) (:inherit font-lock-comment-face))))
 '(info-file ((((class color) (min-colors 89)) (:foreground "#e7c547" :background "#2a2a2a"))))
 '(info-function-ref-item ((((class color) (min-colors 89)) (:inherit font-lock-function-name-face :background "#2a2a2a"))))
 '(info-macro-ref-item ((((class color) (min-colors 89)) (:foreground "#e78c45" :background "#2a2a2a"))))
 '(info-menu ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(info-quoted-name ((((class color) (min-colors 89)) (:inherit font-lock-constant-face))))
 '(info-reference-item ((((class color) (min-colors 89)) (:background "#2a2a2a"))))
 '(info-single-quote ((((class color) (min-colors 89)) (:inherit font-lock-keyword-face))))
 '(info-special-form-ref-item ((((class color) (min-colors 89)) (:foreground "#e78c45" :background "#2a2a2a"))))
 '(info-string ((((class color) (min-colors 89)) (:inherit font-lock-string-face))))
 '(info-syntax-class-item ((((class color) (min-colors 89)) (:foreground "#7aa6da" :background "#2a2a2a"))))
 '(info-user-option-ref-item ((((class color) (min-colors 89)) (:foreground "#d54e53" :background "#2a2a2a"))))
 '(info-variable-ref-item ((((class color) (min-colors 89)) (:inherit font-lock-variable-name-face :background "#2a2a2a"))))
 '(info-xref-bookmarked ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(hi-black-hb ((((class color) (min-colors 89)) (:weight bold :height 1.4))))
 '(hi-blue ((((class color) (min-colors 89)) (:foreground "#000000" :background "#7aa6da"))))
 '(hi-blue-b ((((class color) (min-colors 89)) (:foreground "#7aa6da" :weight bold))))
 '(hi-green ((((class color) (min-colors 89)) (:foreground "#000000" :background "#b9ca4a"))))
 '(hi-green-b ((((class color) (min-colors 89)) (:foreground "#b9ca4a" :weight bold))))
 '(hi-pink ((((class color) (min-colors 89)) (:foreground "#000000" :background "#70c0b1"))))
 '(hi-red-b ((((class color) (min-colors 89)) (:foreground "#d54e53" :weight bold))))
 '(hi-yellow ((((class color) (min-colors 89)) (:foreground "#000000" :background "#e7c547"))))
 '(hl-sexp-face ((((class color) (min-colors 89)) (:background "#424242"))))
 '(highlight-symbol-face ((((class color) (min-colors 89)) (:inherit highlight))))
 '(highlight-80+ ((((class color) (min-colors 89)) (:background "#424242"))))
 '(symbol-overlay-temp-face ((((class color) (min-colors 89)) (:inherit highlight))))
 '(ruler-mode-column-number ((((class color) (min-colors 89)) (:foreground "#eaeaea" :background "#2a2a2a"))))
 '(ruler-mode-comment-column ((((class color) (min-colors 89)) (:foreground "#969896" :background "#424242"))))
 '(ruler-mode-current-column ((((class color) (min-colors 89)) (:foreground "#e7c547" :background "#424242" :weight bold))))
 '(ruler-mode-default ((((class color) (min-colors 89)) (:foreground "#969896" :background "#2a2a2a"))))
 '(ruler-mode-fill-column ((((class color) (min-colors 89)) (:foreground "#d54e53" :background "#424242"))))
 '(ruler-mode-fringes ((((class color) (min-colors 89)) (:foreground "#b9ca4a" :background "#424242"))))
 '(ruler-mode-goal-column ((((class color) (min-colors 89)) (:foreground "#d54e53" :background "#424242"))))
 '(ruler-mode-margins ((((class color) (min-colors 89)) (:foreground "#e78c45" :background "#424242"))))
 '(ruler-mode-pad ((((class color) (min-colors 89)) (:foreground "#000000" :background "#969896"))))
 '(ruler-mode-tab-stop ((((class color) (min-colors 89)) (:foreground "#7aa6da" :background "#424242"))))
 '(hydra-face-blue ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(hydra-face-teal ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(hydra-face-pink ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(hydra-face-red ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(hydra-face-amaranth ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(py-builtins-face ((((class color) (min-colors 89)) (:foreground "#e78c45" :weight normal))))
 '(js2-warning ((((class color) (min-colors 89)) (:underline "#e78c45"))))
 '(js2-error ((((class color) (min-colors 89)) (:foreground nil :underline "#d54e53"))))
 '(js2-external-variable ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(js2-function-param ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(js2-instance-member ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(js2-private-function-call ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(js2-jsdoc-tag ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(js2-jsdoc-type ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(js2-jsdoc-value ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(js2-function-call ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(js2-object-property ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(js2-private-member ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(js2-jsdoc-html-tag-name ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(js2-jsdoc-html-tag-delimiter ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(js3-warning-face ((((class color) (min-colors 89)) (:underline "#e78c45"))))
 '(js3-error-face ((((class color) (min-colors 89)) (:foreground nil :underline "#d54e53"))))
 '(js3-external-variable-face ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(js3-function-param-face ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(js3-jsdoc-tag-face ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(js3-jsdoc-type-face ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(js3-jsdoc-value-face ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(js3-jsdoc-html-tag-name-face ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(js3-jsdoc-html-tag-delimiter-face ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(js3-instance-member-face ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(js3-private-function-call-face ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(coffee-mode-class-name ((((class color) (min-colors 89)) (:foreground "#e78c45" :weight bold))))
 '(coffee-mode-function-param ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(nxml-name-face ((((class color) (min-colors 89)) (:foreground unspecified :inherit font-lock-constant-face))))
 '(nxml-attribute-local-name-face ((((class color) (min-colors 89)) (:foreground unspecified :inherit font-lock-variable-name-face))))
 '(nxml-ref-face ((((class color) (min-colors 89)) (:foreground unspecified :inherit font-lock-preprocessor-face))))
 '(nxml-delimiter-face ((((class color) (min-colors 89)) (:foreground unspecified :inherit font-lock-keyword-face))))
 '(nxml-delimited-data-face ((((class color) (min-colors 89)) (:foreground unspecified :inherit font-lock-string-face))))
 '(rng-error-face ((((class color) (min-colors 89)) (:underline "#d54e53"))))
 '(erb-delim-face ((((class color) (min-colors 89)) (:background "#424242"))))
 '(erb-exec-face ((((class color) (min-colors 89)) (:background "#424242" :weight bold))))
 '(erb-exec-delim-face ((((class color) (min-colors 89)) (:background "#424242"))))
 '(erb-out-face ((((class color) (min-colors 89)) (:background "#424242" :weight bold))))
 '(erb-out-delim-face ((((class color) (min-colors 89)) (:background "#424242"))))
 '(erb-comment-face ((((class color) (min-colors 89)) (:background "#424242" :weight bold :slant italic))))
 '(erb-comment-delim-face ((((class color) (min-colors 89)) (:background "#424242"))))
 '(message-header-other ((((class color) (min-colors 89)) (:foreground nil :background nil :weight normal))))
 '(message-header-subject ((((class color) (min-colors 89)) (:inherit message-header-other :weight bold :foreground "#e7c547"))))
 '(message-header-to ((((class color) (min-colors 89)) (:inherit message-header-other :weight bold :foreground "#e78c45"))))
 '(message-header-cc ((((class color) (min-colors 89)) (:inherit message-header-to :foreground nil))))
 '(message-header-name ((((class color) (min-colors 89)) (:foreground "#7aa6da" :background nil))))
 '(message-header-newsgroups ((((class color) (min-colors 89)) (:foreground "#70c0b1" :background nil :slant normal))))
 '(message-separator ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(jabber-chat-prompt-local ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(jabber-chat-prompt-foreign ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(jabber-chat-prompt-system ((((class color) (min-colors 89)) (:foreground "#e7c547" :weight bold))))
 '(jabber-chat-text-local ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(jabber-chat-text-foreign ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(jabber-chat-text-error ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(jabber-roster-user-online ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(jabber-roster-user-xa ((((class color) (min-colors 89)) :foreground "#969896")))
 '(jabber-roster-user-dnd ((((class color) (min-colors 89)) :foreground "#e7c547")))
 '(jabber-roster-user-away ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(jabber-roster-user-chatty ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(jabber-roster-user-error ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(jabber-roster-user-offline ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(jabber-rare-time-face ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(jabber-activity-face ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(jabber-activity-personal-face ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(powerline-active1 ((((class color) (min-colors 89)) (:foreground "#eaeaea" :background "#2a2a2a"))))
 '(powerline-active2 ((((class color) (min-colors 89)) (:foreground "#eaeaea" :background "#424242"))))
 '(powerline-evil-base-face ((((class color) (min-colors 89)) (:inherit mode-line :foreground "#000000"))))
 '(powerline-evil-emacs-face ((((class color) (min-colors 89)) (:inherit powerline-evil-base-face :background "#c397d8"))))
 '(powerline-evil-insert-face ((((class color) (min-colors 89)) (:inherit powerline-evil-base-face :background "#7aa6da"))))
 '(powerline-evil-motion-face ((((class color) (min-colors 89)) (:inherit powerline-evil-base-face :background "#e78c45"))))
 '(powerline-evil-normal-face ((((class color) (min-colors 89)) (:inherit powerline-evil-base-face :background "#b9ca4a"))))
 '(powerline-evil-operator-face ((((class color) (min-colors 89)) (:inherit powerline-evil-base-face :background "#70c0b1"))))
 '(powerline-evil-replace-face ((((class color) (min-colors 89)) (:inherit powerline-evil-base-face :background "#d54e53"))))
 '(powerline-evil-visual-face ((((class color) (min-colors 89)) (:inherit powerline-evil-base-face :background "#e7c547"))))
 '(outline-1 ((((class color) (min-colors 89)) (:inherit nil :foreground "#7aa6da"))))
 '(outline-2 ((((class color) (min-colors 89)) (:inherit nil :foreground "#c397d8"))))
 '(outline-3 ((((class color) (min-colors 89)) (:inherit nil :foreground "#70c0b1"))))
 '(outline-4 ((((class color) (min-colors 89)) (:inherit nil :foreground "#e7c547"))))
 '(outline-5 ((((class color) (min-colors 89)) (:inherit nil :foreground "#e78c45"))))
 '(outline-6 ((((class color) (min-colors 89)) (:inherit nil :foreground "#7aa6da"))))
 '(outline-7 ((((class color) (min-colors 89)) (:inherit nil :foreground "#c397d8"))))
 '(outline-8 ((((class color) (min-colors 89)) (:inherit nil :foreground "#70c0b1"))))
 '(outline-9 ((((class color) (min-colors 89)) (:inherit nil :foreground "#e7c547"))))
 '(ledger-font-comment-face ((((class color) (min-colors 89)) (:inherit font-lock-comment-face))))
 '(ledger-font-occur-narrowed-face ((((class color) (min-colors 89)) (:inherit font-lock-comment-face :invisible t))))
 '(ledger-font-occur-xact-face ((((class color) (min-colors 89)) (:inherit highlight))))
 '(ledger-font-payee-cleared-face ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(ledger-font-payee-uncleared-face ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(ledger-font-posting-date-face ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(ledger-font-posting-amount-face ((((class color) (min-colors 89)) (:foreground "#eaeaea"))))
 '(ledger-font-posting-account-cleared-face ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(ledger-font-posting-account-face ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(ledger-font-posting-account-pending-face ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(ledger-font-xact-highlight-face ((((class color) (min-colors 89)) (:inherit highlight))))
 '(ledger-occur-narrowed-face ((((class color) (min-colors 89)) (:inherit font-lock-comment-face :invisible t))))
 '(ledger-occur-xact-face ((((class color) (min-colors 89)) (:inherit highlight))))
 '(elfeed-log-debug-level-face ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(elfeed-log-error-level-face ((((class color) (min-colors 89)) (:inherit error))))
 '(elfeed-log-info-level-face ((((class color) (min-colors 89)) (:inherit success))))
 '(elfeed-log-warn-level-face ((((class color) (min-colors 89)) (:inherit warning))))
 '(elfeed-search-date-face ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(elfeed-search-feed-face ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(elfeed-search-tag-face ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(elfeed-search-title-face ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(elfeed-search-unread-count-face ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(elfeed-search-unread-title-face ((((class color) (min-colors 89)) (:foreground "#eaeaea" :weight bold))))
 '(emms-browser-artist-face ((((class color) (min-colors 89)) (:inherit outline-2))))
 '(emms-browser-album-face ((((class color) (min-colors 89)) (:inherit outline-3))))
 '(emms-browser-track-face ((((class color) (min-colors 89)) (:inherit outline-4))))
 '(emms-browser-year/genre-face ((((class color) (min-colors 89)) (:inherit outline-1))))
 '(emms-playlist-selected-face ((((class color) (min-colors 89)) (:inverse-video t))))
 '(emms-playlist-track-face ((((class color) (min-colors 89)) (:inherit outline-4))))
 '(debbugs-gnu-done ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(debbugs-gnu-handled ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(debbugs-gnu-new ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(debbugs-gnu-pending ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(debbugs-gnu-stale ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(debbugs-gnu-tagged ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(mu4e-header-highlight-face ((((class color) (min-colors 89)) (:underline nil :inherit region))))
 '(mu4e-header-marks-face ((((class color) (min-colors 89)) (:underline nil :foreground "#e7c547"))))
 '(mu4e-flagged-face ((((class color) (min-colors 89)) (:foreground "#e78c45" :inherit nil))))
 '(mu4e-replied-face ((((class color) (min-colors 89)) (:foreground "#7aa6da" :inherit nil))))
 '(mu4e-unread-face ((((class color) (min-colors 89)) (:foreground "#e7c547" :inherit nil))))
 '(mu4e-cited-1-face ((((class color) (min-colors 89)) (:inherit outline-1 :slant normal))))
 '(mu4e-cited-2-face ((((class color) (min-colors 89)) (:inherit outline-2 :slant normal))))
 '(mu4e-cited-3-face ((((class color) (min-colors 89)) (:inherit outline-3 :slant normal))))
 '(mu4e-cited-4-face ((((class color) (min-colors 89)) (:inherit outline-4 :slant normal))))
 '(mu4e-cited-5-face ((((class color) (min-colors 89)) (:inherit outline-5 :slant normal))))
 '(mu4e-cited-6-face ((((class color) (min-colors 89)) (:inherit outline-6 :slant normal))))
 '(mu4e-cited-7-face ((((class color) (min-colors 89)) (:inherit outline-7 :slant normal))))
 '(mu4e-ok-face ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(mu4e-view-contact-face ((((class color) (min-colors 89)) (:inherit nil :foreground "#e7c547"))))
 '(mu4e-view-link-face ((((class color) (min-colors 89)) (:inherit link :foreground "#7aa6da"))))
 '(mu4e-view-url-number-face ((((class color) (min-colors 89)) (:inherit nil :foreground "#70c0b1"))))
 '(mu4e-view-attach-number-face ((((class color) (min-colors 89)) (:inherit nil :foreground "#e78c45"))))
 '(mu4e-highlight-face ((((class color) (min-colors 89)) (:inherit highlight))))
 '(mu4e-title-face ((((class color) (min-colors 89)) (:inherit nil :foreground "#b9ca4a"))))
 '(gnus-button ((((class color) (min-colors 89)) (:inherit link :foreground nil))))
 '(gnus-emphasis-highlight-words ((((class color) (min-colors 89)) (:foreground "#e7c547" :background "#2a2a2a"))))
 '(gnus-header-content ((((class color) (min-colors 89)) (:inherit message-header-other))))
 '(gnus-header-from ((((class color) (min-colors 89)) (:inherit message-header-other-face :weight bold :foreground "#e78c45"))))
 '(gnus-header-name ((((class color) (min-colors 89)) (:inherit message-header-name))))
 '(gnus-header-newsgroups ((((class color) (min-colors 89)) (:foreground "#e7c547" :slant italic))))
 '(gnus-header-subject ((((class color) (min-colors 89)) (:inherit message-header-subject))))
 '(gnus-x-face ((((class color) (min-colors 89)) (:foreground "#000000" :background "#eaeaea"))))
 '(gnus-signature ((((class color) (min-colors 89)) (:inherit font-lock-comment-face))))
 '(mm-uu-extract ((((class color) (min-colors 89)) (:foreground "#b9ca4a" :background "#2a2a2a"))))
 '(gnus-cite-1 ((((class color) (min-colors 89)) (:inherit outline-1 :foreground nil))))
 '(gnus-cite-2 ((((class color) (min-colors 89)) (:inherit outline-2 :foreground nil))))
 '(gnus-cite-3 ((((class color) (min-colors 89)) (:inherit outline-3 :foreground nil))))
 '(gnus-cite-4 ((((class color) (min-colors 89)) (:inherit outline-4 :foreground nil))))
 '(gnus-cite-5 ((((class color) (min-colors 89)) (:inherit outline-5 :foreground nil))))
 '(gnus-cite-6 ((((class color) (min-colors 89)) (:inherit outline-6 :foreground nil))))
 '(gnus-cite-7 ((((class color) (min-colors 89)) (:inherit outline-7 :foreground nil))))
 '(gnus-cite-8 ((((class color) (min-colors 89)) (:inherit outline-8 :foreground nil))))
 '(gnus-cite-9 ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(gnus-cite-10 ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(gnus-cite-11 ((((class color) (min-colors 89)) (:foreground "#424242"))))
 '(gnus-group-mail-1 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-1))))
 '(gnus-group-mail-1-empty ((((class color) (min-colors 89)) (:inherit gnus-group-mail-1 :foreground "#969896"))))
 '(gnus-group-mail-2 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-2))))
 '(gnus-group-mail-2-empty ((((class color) (min-colors 89)) (:inherit gnus-group-mail-2 :foreground "#969896"))))
 '(gnus-group-mail-3 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-3))))
 '(gnus-group-mail-3-empty ((((class color) (min-colors 89)) (:inherit gnus-group-mail-3 :foreground "#969896"))))
 '(gnus-group-mail-4 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-4))))
 '(gnus-group-mail-4-empty ((((class color) (min-colors 89)) (:inherit gnus-group-mail-4 :foreground "#969896"))))
 '(gnus-group-mail-5 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-5))))
 '(gnus-group-mail-5-empty ((((class color) (min-colors 89)) (:inherit gnus-group-mail-5 :foreground "#969896"))))
 '(gnus-group-mail-6 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-6))))
 '(gnus-group-mail-6-empty ((((class color) (min-colors 89)) (:inherit gnus-group-mail-6 :foreground "#969896"))))
 '(gnus-group-mail-low ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(gnus-group-mail-low-empty ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(gnus-group-news-1 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-1))))
 '(gnus-group-news-1-empty ((((class color) (min-colors 89)) (:inherit gnus-group-news-1 :foreground "#969896"))))
 '(gnus-group-news-2 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-2))))
 '(gnus-group-news-2-empty ((((class color) (min-colors 89)) (:inherit gnus-group-news-2 :foreground "#969896"))))
 '(gnus-group-news-3 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-3))))
 '(gnus-group-news-3-empty ((((class color) (min-colors 89)) (:inherit gnus-group-news-3 :foreground "#969896"))))
 '(gnus-group-news-4 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-4))))
 '(gnus-group-news-4-empty ((((class color) (min-colors 89)) (:inherit gnus-group-news-4 :foreground "#969896"))))
 '(gnus-group-news-5 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-5))))
 '(gnus-group-news-5-empty ((((class color) (min-colors 89)) (:inherit gnus-group-news-5 :foreground "#969896"))))
 '(gnus-group-news-6 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-6))))
 '(gnus-group-news-6-empty ((((class color) (min-colors 89)) (:inherit gnus-group-news-6 :foreground "#969896"))))
 '(gnus-server-agent ((((class color) (min-colors 89)) (:foreground "#70c0b1" :weight bold))))
 '(gnus-server-closed ((((class color) (min-colors 89)) (:foreground "#969896" :slant italic))))
 '(gnus-server-cloud ((((class color) (min-colors 89)) (:foreground "#e78c45" :weight bold))))
 '(gnus-server-denied ((((class color) (min-colors 89)) (:foreground "#d54e53" :weight bold))))
 '(gnus-server-offline ((((class color) (min-colors 89)) (:foreground "#7aa6da" :weight bold))))
 '(gnus-server-opened ((((class color) (min-colors 89)) (:foreground "#b9ca4a" :weight bold))))
 '(gnus-splash ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(gnus-summary-cancelled ((((class color) (min-colors 89)) (:foreground "#d54e53" :background nil :weight normal))))
 '(gnus-summary-high-ancient ((((class color) (min-colors 89)) (:foreground "#b9ca4a" :weight normal))))
 '(gnus-summary-high-read ((((class color) (min-colors 89)) (:foreground "#b9ca4a" :weight normal))))
 '(gnus-summary-high-ticked ((((class color) (min-colors 89)) (:foreground "#e78c45" :weight normal))))
 '(gnus-summary-high-undownloaded ((((class color) (min-colors 89)) (:foreground "#eaeaea" :weight bold))))
 '(gnus-summary-high-unread ((((class color) (min-colors 89)) (:foreground "#e7c547" :weight normal))))
 '(gnus-summary-low-ancient ((((class color) (min-colors 89)) (:foreground "#969896" :weight normal))))
 '(gnus-summary-low-read ((((class color) (min-colors 89)) (:foreground "#969896" :weight normal))))
 '(gnus-summary-low-ticked ((((class color) (min-colors 89)) (:foreground "#969896" :slant italic))))
 '(gnus-summary-low-undownloaded ((((class color) (min-colors 89)) (:foreground "#eaeaea" :slant italic))))
 '(gnus-summary-low-unread ((((class color) (min-colors 89)) (:foreground "#969896" :weight normal))))
 '(gnus-summary-normal-ancient ((((class color) (min-colors 89)) (:foreground "#70c0b1" :weight normal))))
 '(gnus-summary-normal-read ((((class color) (min-colors 89)) (:foreground "#eaeaea" :weight normal))))
 '(gnus-summary-normal-ticked ((((class color) (min-colors 89)) (:foreground "#e78c45" :weight normal))))
 '(gnus-summary-normal-undownloaded ((((class color) (min-colors 89)) (:foreground "#eaeaea"))))
 '(gnus-summary-normal-unread ((((class color) (min-colors 89)) (:foreground "#7aa6da" :weight normal))))
 '(circe-fool-face ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(circe-highlight-nick-face ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(circe-my-message-face ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(circe-prompt-face ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(circe-server-face ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(circe-topic-diff-new-face ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(circe-topic-diff-removed-face ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(erc-direct-msg-face ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(erc-error-face ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(erc-header-face ((((class color) (min-colors 89)) (:foreground "#eaeaea" :background "#2a2a2a"))))
 '(erc-input-face ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(erc-current-nick-face ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(erc-my-nick-face ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(erc-nick-default-face ((((class color) (min-colors 89)) (:weight normal :foreground "#c397d8"))))
 '(erc-nick-msg-face ((((class color) (min-colors 89)) (:weight normal :foreground "#e7c547"))))
 '(erc-notice-face ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(erc-pal-face ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(erc-prompt-face ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(erc-timestamp-face ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(erc-keyword-face ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(rcirc-bright-nick ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(rcirc-dim-nick ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(rcirc-keyword ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(rcirc-my-nick ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(rcirc-nick-in-message ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(rcirc-nick-in-message-full-line ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(rcirc-other-nick ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(rcirc-prompt ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(rcirc-server ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(rcirc-timestamp ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(twittering-username-face ((((class color) (min-colors 89)) (:inherit erc-pal-face))))
 '(twittering-uri-face ((((class color) (min-colors 89)) (:foreground "#7aa6da" :inherit link))))
 '(twittering-timeline-header-face ((((class color) (min-colors 89)) (:foreground "#b9ca4a" :weight bold))))
 '(twittering-timeline-footer-face ((((class color) (min-colors 89)) (:inherit twittering-timeline-header-face))))
 '(custom-variable-tag ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(custom-group-tag ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(custom-state ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(term ((((class color) (min-colors 89)) (:foreground nil :background nil :inherit default))))
 '(term-color-black ((((class color) (min-colors 89)) (:foreground "#eaeaea" :background "#eaeaea"))))
 '(term-color-red ((((class color) (min-colors 89)) (:foreground "#d54e53" :background "#d54e53"))))
 '(term-color-green ((((class color) (min-colors 89)) (:foreground "#b9ca4a" :background "#b9ca4a"))))
 '(term-color-yellow ((((class color) (min-colors 89)) (:foreground "#e7c547" :background "#e7c547"))))
 '(term-color-blue ((((class color) (min-colors 89)) (:foreground "#7aa6da" :background "#7aa6da"))))
 '(term-color-magenta ((((class color) (min-colors 89)) (:foreground "#c397d8" :background "#c397d8"))))
 '(term-color-cyan ((((class color) (min-colors 89)) (:foreground "#70c0b1" :background "#70c0b1"))))
 '(term-color-white ((((class color) (min-colors 89)) (:foreground "#000000" :background "#000000"))))
 '(eshell-prompt ((((class color) (min-colors 89)) (:foreground "#e7c547" :weight bold))))
 '(eshell-ls-archive ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(eshell-ls-backup ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(eshell-ls-clutter ((((class color) (min-colors 89)) (:foreground "#e78c45" :weight bold))))
 '(eshell-ls-directory ((((class color) (min-colors 89)) :foreground "#7aa6da" :weight bold)))
 '(eshell-ls-executable ((((class color) (min-colors 89)) (:foreground "#e7c547" :weight bold))))
 '(eshell-ls-missing ((((class color) (min-colors 89)) (:foreground "#d54e53" :weight bold))))
 '(eshell-ls-product ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(eshell-ls-readonly ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(eshell-ls-special ((((class color) (min-colors 89)) (:foreground "#c397d8" :weight bold))))
 '(eshell-ls-symlink ((((class color) (min-colors 89)) (:foreground "#70c0b1" :weight bold))))
 '(eshell-ls-unreadable ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(e2wm:face-history-list-normal ((((class color) (min-colors 89)) (:foreground "#eaeaea" :background "#000000"))))
 '(e2wm:face-history-list-select1 ((((class color) (min-colors 89)) (:foreground "#70c0b1" :background "#000000"))))
 '(e2wm:face-history-list-select2 ((((class color) (min-colors 89)) (:foreground "#e7c547" :background "#000000"))))
 '(eyebrowse-mode-line-active ((((class color) (min-colors 89)) (:foreground "#e78c45" :weight bold))))
 '(eyebrowse-mode-line-delimiters ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(eyebrowse-mode-line-inactive ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(eyebrowse-mode-line-separator ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(rpm-spec-dir-face ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(rpm-spec-doc-face ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(rpm-spec-ghost-face ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(rpm-spec-macro-face ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(rpm-spec-obsolete-tag-face ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(rpm-spec-package-face ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(rpm-spec-section-face ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(rpm-spec-tag-face ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(rpm-spec-var-face ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(sx-question-mode-content-face ((((class color) (min-colors 89)) (:background "#2a2a2a"))))
 '(sx-question-list-answers ((((class color) (min-colors 89)) (:height 1.0 :inherit sx-question-list-parent :foreground "#b9ca4a"))))
 '(sx-question-mode-accepted ((((class color) (min-colors 89)) (:height 1.5 :inherit sx-question-mode-title :foreground "#b9ca4a"))))
 '(sx-question-mode-kbd-tag ((((class color) (min-colors 89)) (:height 0.9 :weight semi-bold :box (:line-width 3 :style released-button :color "#424242")))))
 '(cscope-file-face ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(cscope-function-face ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(cscope-line-number-face ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(cscope-separator-face ((((class color) (min-colors 89)) (:bold t :overline t :underline t :foreground "#c397d8"))))
 '(default ((((class color) (min-colors 89)) (:foreground "#eaeaea" :background "#000000")))))

(provide-theme 'hw)
